apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yfr2919sc-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/yfr2919sc-java-quarkus-gitops